shopping_list=[]#告诉代码，这是数组
shopping_list.append("键盘")#告诉代码，这是append是要添加到数组中的元素
shopping_list.append("键帽")
shopping_list.append("音响")
shopping_list.append("电竞椅子")
shopping_list.remove("音响")#输入remove和字符串，代表要在数组中删去的元素
shopping_list[1]="硬盘"#输入数组的索引位置，和新字符串，表示要替换的数组元素
shopping_list[2]="颈椎按摩器"
print(shopping_list)
print(len(shopping_list))
print(shopping_list[1])
price=[299,199,399]
max_price=max(price)
min_price=min(price)
sorted_price=sorted(price)
print(max_price)
print(min_price)
print(sorted_price)